server:
  port: 8100
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8869/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug